"""Cross-source dispatch scoring (AGGRESSION RULING 2026-09-18, step 2 as revised).

The diagnosis that produced this: the funnel is selection-constrained, not
supply-constrained. Form 8-K ran 87-254 candidates a day against a cap of 6,
congressional 70-213 against 5, and the caps were filled by ARRIVAL ORDER
within each source — whichever candidates the poll happened to deliver first
spent the day's slots. This module makes the slots compete on a score that is
comparable across families, so the floor is competition, not arrival.

The score, in one unit — expected five-day excess return, in percent:

    score = prior(slice) - age_days x freshness_points_per_day + convergence bonus

* ``prior`` is the slice's measured mean excess from the forward-return engine
  where the sample permits (``n >= min_n``), else the source's RULED fallback,
  and the file says which it is (``grounded``). Slices are built from the
  structured facts each fetcher already stamps: 8-K by whitelisted item, Form 4
  by door and aggregate size, congressional by amount band and disclosure lag,
  13D by stake. Posts and callers score at their source fallback.
* freshness keeps the 2026-08-26 equivalence (one week of age = one point) so
  same-slice candidates dispatch fresher-first.
* the registry's convergence bonus rides along unchanged (ruling 2026-09-01).

ORDERING ONLY, and deterministic: every input is a structured feed field, a
config value, or the system's own forward-return record — never the content of
a post, never an LLM. Per-source caps stay as ceilings so no source can take the
day; the class pools stay; what changes is WHICH candidates spend them.

``config/dispatch_priors.yaml`` is generated by ``python -m orchestrator priors``
from the forward engine and committed by a human — data argues, humans rule.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Optional

import yaml

from audit.records import (
    snapshot_8k_items,
    snapshot_amount_range,
    snapshot_form4_qualification,
    snapshot_lag_days,
)
from signals import Signal

PRIORS_PATH = Path(__file__).resolve().parents[2] / "config" / "dispatch_priors.yaml"

_NUMBERS = re.compile(r"\d[\d,]*")
_AGGREGATE = re.compile(r"aggregate \$([\d,]+)")
_STAKE = re.compile(r"^stake:\s*([\d.]+)% of class", re.MULTILINE)

#: The 8-K whitelist in the order the ruling ranks informativeness (5.02 and
#: 1.05 ahead of 1.01). A filing carrying several whitelisted items takes the
#: facet of its highest-ranked one.
EIGHT_K_ITEM_ORDER: tuple[str, ...] = ("5.02", "1.05", "4.02", "2.05", "1.01")


# ------------------------------------------------------------------ facets


def amount_max(rendered: str) -> Optional[int]:
    figures = [int(m.replace(",", "")) for m in _NUMBERS.findall(str(rendered or ""))]
    return max(figures) if figures else None


def amount_band(dollars: Optional[int]) -> str:
    if dollars is None:
        return "unknown"
    for ceiling, label in (
        (15_000, "<=15K"),
        (50_000, "<=50K"),
        (100_000, "<=100K"),
        (250_000, "<=250K"),
        (1_000_000, "<=1M"),
        (5_000_000, "<=5M"),
    ):
        if dollars <= ceiling:
            return label
    return ">5M"


def lag_band(days: Optional[int]) -> str:
    if days is None:
        return "unknown"
    if days <= 7:
        return "<=7d"
    if days <= 20:
        return "<=20d"
    if days <= 35:
        return "<=35d"
    return ">35d"


def stake_band(percent: Optional[Decimal | float]) -> str:
    if percent is None:
        return "unknown"
    value = float(percent)
    if value < 5:
        return "<5%"
    if value < 10:
        return "5-10%"
    return ">=10%"


def facet_8k(items: Iterable[str]) -> str:
    present = {str(i).strip() for i in items}
    for item in EIGHT_K_ITEM_ORDER:
        if item in present:
            return f"item={item}"
    return "item=other"


def facet_form4(qualification: str, aggregate: Optional[int]) -> str:
    return f"qual={qualification or 'unparsed'}|size={amount_band(aggregate)}"


def facet_congressional(amount: Optional[int], lag_days: Optional[int]) -> str:
    return f"amount={amount_band(amount)}|lag={lag_band(lag_days)}"


def facet_13d(stake: Optional[Decimal | float]) -> str:
    return f"stake={stake_band(stake)}"


def facet_of_content(source_id: str, content: str) -> str:
    """The slice facet from the content a fetcher wrote — what the audit log
    keeps, so records before any structured field grade the same way."""

    class _Snap:  # the snapshot parsers only read .content / .tickers
        tickers = ()

        def __init__(self, text: str) -> None:
            self.content = text

    snap = _Snap(content or "")
    if source_id == "form_8k":
        return facet_8k(snapshot_8k_items(snap))
    if source_id == "form4_insiders":
        match = _AGGREGATE.search(content or "")
        aggregate = int(match.group(1).replace(",", "")) if match else None
        return facet_form4(snapshot_form4_qualification(snap), aggregate)
    if source_id == "congressional_disclosures":
        return facet_congressional(
            amount_max(snapshot_amount_range(snap)), snapshot_lag_days(snap)
        )
    if source_id == "form_13d":
        match = _STAKE.search(content or "")
        return facet_13d(Decimal(match.group(1)) if match else None)
    return ""


def facet_of_signal(signal: Signal) -> str:
    """The slice facet at dispatch time: the fetcher's structured fields first,
    the content parsers where a field is missing."""
    meta = signal.metadata
    if signal.source_id == "form_8k":
        listed = meta.get("whitelisted_items") or meta.get("items") or ""
        items = [p.strip() for p in str(listed).split(",") if p.strip()]
        return facet_8k(items) if items else facet_of_content(signal.source_id, signal.content)
    if signal.source_id == "form4_insiders":
        qual = meta.get("qualifies") or snapshot_form4_qualification(signal)
        aggregate = amount_max(meta.get("amount_range", ""))
        if aggregate is None:
            match = _AGGREGATE.search(signal.content or "")
            aggregate = int(match.group(1).replace(",", "")) if match else None
        return facet_form4(str(qual), aggregate)
    if signal.source_id == "congressional_disclosures":
        amount = amount_max(meta.get("amount_range") or snapshot_amount_range(signal))
        raw_lag = str(meta.get("disclosure_lag_days") or "").strip()
        lag = int(raw_lag) if raw_lag.isdigit() else snapshot_lag_days(signal)
        return facet_congressional(amount, lag)
    if signal.source_id == "form_13d":
        raw = str(meta.get("percent_of_class") or "").strip().rstrip("%")
        try:
            stake: Optional[Decimal] = Decimal(raw) if raw else None
        except Exception:  # noqa: BLE001 - an unparseable stake is unknown
            stake = None
        return facet_13d(stake)
    return ""


# ------------------------------------------------------------------ priors


@dataclass(frozen=True, slots=True)
class SlicePrior:
    prior: float
    grounded: bool
    n: int = 0
    note: str = ""


@dataclass(frozen=True, slots=True)
class SourcePriors:
    fallback: float
    slices: Mapping[str, SlicePrior] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DispatchPriors:
    """The committed priors file. ``prior_for`` resolves a facet exactly, then by
    each single facet in turn (``qual=cluster|size=<=1M`` falls back to
    ``qual=cluster``), then to the source's fallback, then to zero."""

    horizon_days: int
    min_n: int
    freshness_points_per_day: float
    sources: Mapping[str, SourcePriors]
    generated_at: str = ""

    @classmethod
    def load(cls, path: Optional[Path] = None) -> "DispatchPriors":
        raw = yaml.safe_load((path or PRIORS_PATH).read_text(encoding="utf-8")) or {}
        return cls.from_mapping(raw)

    @classmethod
    def from_mapping(cls, raw: Mapping[str, Any]) -> "DispatchPriors":
        sources: dict[str, SourcePriors] = {}
        for source_id, block in (raw.get("sources") or {}).items():
            block = block or {}
            slices = {}
            for facet, spec in (block.get("slices") or {}).items():
                spec = spec or {}
                if "prior" not in spec:
                    continue  # sample-size bookkeeping only; resolves through its facets
                slices[str(facet)] = SlicePrior(
                    prior=float(spec.get("prior", 0.0)),
                    grounded=bool(spec.get("grounded", False)),
                    n=int(spec.get("n", 0) or 0),
                    note=str(spec.get("note", "")),
                )
            sources[str(source_id)] = SourcePriors(
                fallback=float(block.get("fallback", 0.0)), slices=slices
            )
        return cls(
            horizon_days=int(raw.get("horizon_days", 5)),
            min_n=int(raw.get("min_n", 20)),
            freshness_points_per_day=float(raw.get("freshness_points_per_day", 1 / 7)),
            sources=sources,
            generated_at=str(raw.get("generated_at", "")),
        )

    def prior_for(self, source_id: str, facet: str) -> tuple[float, bool, str]:
        """(prior, grounded, resolved-facet)."""
        source = self.sources.get(source_id)
        if source is None:
            return 0.0, False, ""
        candidates = [facet] if facet else []
        if facet and "|" in facet:
            candidates.extend(facet.split("|"))
        for key in candidates:
            hit = source.slices.get(key)
            if hit is not None:
                return hit.prior, hit.grounded, key
        return source.fallback, False, "fallback"


# ------------------------------------------------------------------ scoring


@dataclass(frozen=True, slots=True)
class DispatchScore:
    source_id: str
    facet: str
    resolved: str
    prior: float
    grounded: bool
    age_days: float
    freshness: float
    bonus: float
    size_log: float

    @property
    def total(self) -> float:
        return self.prior + self.freshness + self.bonus

    def line(self) -> str:
        tag = "grounded" if self.grounded else "ruled"
        return (
            f"{self.total:+.2f} = prior {self.prior:+.2f} ({self.resolved or self.facet or 'source'}, {tag})"
            f" {self.freshness:+.2f} age {self.bonus:+.2f} conv"
        )


def _age_days(signal: Signal, now: datetime) -> float:
    raw = str(signal.metadata.get("report_date") or "")[:10]
    try:
        reported = date.fromisoformat(raw)
    except ValueError:
        return 0.0
    return float(max((now.date() - reported).days, 0))


def _size_log(signal: Signal) -> float:
    dollars = amount_max(signal.metadata.get("amount_range", ""))
    if dollars is None:
        match = _AGGREGATE.search(signal.content or "")
        dollars = int(match.group(1).replace(",", "")) if match else None
    return math.log10(dollars) if dollars else 0.0


class DispatchScorer:
    """Scores signals for the dispatch sort. ``bonus`` is the registry's
    convergence bonus function (or None)."""

    def __init__(
        self,
        priors: DispatchPriors,
        bonus: Optional[Callable[[Signal], Any]] = None,
    ) -> None:
        self._priors = priors
        self._bonus = bonus

    @property
    def priors(self) -> DispatchPriors:
        return self._priors

    def score(self, signal: Signal, now: datetime) -> DispatchScore:
        facet = facet_of_signal(signal)
        prior, grounded, resolved = self._priors.prior_for(signal.source_id, facet)
        age = _age_days(signal, now)
        bonus = float(self._bonus(signal)) if self._bonus is not None else 0.0
        return DispatchScore(
            source_id=signal.source_id,
            facet=facet,
            resolved=resolved,
            prior=prior,
            grounded=grounded,
            age_days=age,
            freshness=-age * self._priors.freshness_points_per_day,
            bonus=bonus,
            size_log=_size_log(signal),
        )

    def sort_key(self, signal: Signal, now: datetime) -> tuple:
        score = self.score(signal, now)
        return (-score.total, -score.size_log, signal.observed_at)


# ------------------------------------------------------------------ grounding


@dataclass(frozen=True, slots=True)
class SliceStat:
    source_id: str
    facet: str
    n: int
    mean: Optional[float]
    median: Optional[float]
    hit_rate: Optional[float]

    def grounded(self, min_n: int) -> bool:
        return self.mean is not None and self.n >= min_n


def compute_slice_stats(
    records: Iterable[Any],
    rows: Mapping[tuple[str, date], Any],
    horizon_days: int,
) -> list[SliceStat]:
    """Mean forward excess by (source, facet) over every funnel record with a
    resolved mark at ``horizon_days`` — researched or not: a capped candidate
    is exactly the observation this needs. Only the first record per decision
    id counts, like the forward funnel. Bearish measurement rows (sell
    clusters) are excluded: they are not candidates for a long."""
    from audit.records import DecisionRecord, StageRejectionRecord, snapshot_tickers

    seen: set[str] = set()
    values: dict[tuple[str, str], list[float]] = {}
    for record in records:
        if not isinstance(record, (DecisionRecord, StageRejectionRecord)):
            continue
        if record.decision_id in seen:
            continue
        seen.add(record.decision_id)
        if isinstance(record, StageRejectionRecord) and record.code in (
            "bearish_measurement",
            "overreaction_candidate",
        ):
            continue
        if isinstance(record, DecisionRecord) and record.sizing.strategy in (
            "mechanical",
            "cash_sweep",
            "baseline",
        ):
            continue
        snapshot = record.signal
        tickers = snapshot_tickers(snapshot)
        if not tickers:
            continue
        row = rows.get((tickers[0].upper(), snapshot.observed_at.date()))
        if row is None:
            continue
        mark = row.marks.get(horizon_days)
        if mark is None or mark.excess_pct is None:
            continue
        facet = facet_of_content(snapshot.source_id, snapshot.content or "")
        values.setdefault((snapshot.source_id, facet), []).append(float(mark.excess_pct))
        if "|" in facet:
            # Single-facet marginals too, so a sparse cell can fall back to a
            # grounded marginal instead of the ruled default.
            for part in facet.split("|"):
                values.setdefault((snapshot.source_id, part), []).append(float(mark.excess_pct))
        values.setdefault((snapshot.source_id, ""), []).append(float(mark.excess_pct))
    out: list[SliceStat] = []
    for (source_id, facet), sample in sorted(values.items()):
        ordered = sorted(sample)
        mid = len(ordered) // 2
        median = ordered[mid] if len(ordered) % 2 else (ordered[mid - 1] + ordered[mid]) / 2
        out.append(
            SliceStat(
                source_id=source_id,
                facet=facet,
                n=len(sample),
                mean=sum(sample) / len(sample),
                median=median,
                hit_rate=sum(1 for v in sample if v > 0) / len(sample),
            )
        )
    return out


def render_slice_stats(stats: list[SliceStat], priors: DispatchPriors) -> str:
    lines = [
        f"Dispatch priors from the forward engine — mean excess at {priors.horizon_days}d, "
        f"grounded where n >= {priors.min_n} (everything else keeps its ruled default):"
    ]
    for stat in stats:
        current, grounded_now, resolved = priors.prior_for(stat.source_id, stat.facet)
        flag = "GROUNDED" if stat.grounded(priors.min_n) else f"n<{priors.min_n}"
        lines.append(
            f"  {stat.source_id:<26} {stat.facet or '(source)':<32} n={stat.n:4d} "
            f"mean={stat.mean:+6.2f} med={stat.median:+6.2f} hit={stat.hit_rate:4.0%}  {flag:<9} "
            f"file: {current:+.2f} ({'grounded' if grounded_now else 'ruled'}, {resolved or 'fallback'})"
        )
    return "\n".join(lines)


def merged_priors_mapping(
    current: Mapping[str, Any], stats: list[SliceStat], generated_at: str
) -> dict[str, Any]:
    """The priors file with every grounded slice replaced by its measurement
    and every other slice left as ruled. Pure: returns the mapping to write."""
    out = yaml.safe_load(yaml.safe_dump(dict(current))) or {}
    out["generated_at"] = generated_at
    min_n = int(out.get("min_n", 20))
    sources = out.setdefault("sources", {})
    for stat in stats:
        if not stat.facet:
            continue  # the source marginal is reported, not written: the fallback is ruled
        block = sources.setdefault(stat.source_id, {"fallback": 0.0, "slices": {}})
        slices = block.setdefault("slices", {})
        spec = dict(slices.get(stat.facet) or {})
        if stat.grounded(min_n):
            spec.update(
                {
                    "prior": round(float(stat.mean), 2),
                    "grounded": True,
                    "n": stat.n,
                    "hit_rate": round(float(stat.hit_rate), 2),
                    "note": f"measured mean {out.get('horizon_days', 5)}d excess, {generated_at[:10]}",
                }
            )
        elif stat.facet in slices:
            # A ruled entry keeps its value; only its sample size is refreshed.
            # An ungrounded slice the file does NOT carry is not written: an
            # entry at the fallback would shadow the single-facet resolution
            # (qual=cluster|size=<=5M at 0.0 would hide qual=cluster at 0.5).
            spec["grounded"] = False
            spec["n"] = stat.n
            spec.setdefault("note", "ruled default; sample too small to ground")
        else:
            continue
        slices[stat.facet] = spec
    return out


# ------------------------------------------------------------------ the counterfactual


#: Rejection codes that mean "reached dispatch as a candidate but did not get a
#: slot": the population the counterfactual ranks alongside what was researched.
SLOT_LOSER_CODES: frozenset[str] = frozenset({"source_cap", "class_cap", "aged_out_capped"})


@dataclass(frozen=True, slots=True)
class Candidate:
    decision_id: str
    source_id: str
    signal_class: str
    facet: str
    prior: float
    grounded: bool
    researched: bool
    symbol: str
    observed: date
    content_head: str


def whatif_dispatch(
    records: Iterable[Any],
    day: date,
    priors: DispatchPriors,
    source_caps: Mapping[str, int],
    class_caps: Optional[Any],
    rows: Mapping[tuple[str, date], Any] = {},
) -> str:
    """What the day's research slots WOULD have gone to under global scoring
    versus what they actually went to (ruling 2026-09-18, revised step 2 item 3).

    Candidates = every first record on ``day`` that reached dispatch: researched
    (paid) records plus slot losers. Each is scored by its slice prior (same-day,
    so freshness is zero; convergence is not replayed). The scored set takes the
    highest priors first under the same per-source ceilings and class pools; the
    two sets are compared by source, by slice, by summed prior, and by realised
    excess where the forward cache already has the marks."""
    from audit.records import DecisionRecord, StageRejectionRecord, snapshot_tickers

    seen: set[str] = set()
    candidates: list[Candidate] = []
    for record in records:
        if not isinstance(record, (DecisionRecord, StageRejectionRecord)):
            continue
        if record.recorded_at.date() != day or record.decision_id in seen:
            continue
        seen.add(record.decision_id)
        paid = False
        if isinstance(record, DecisionRecord):
            if record.sizing.strategy in ("mechanical", "cash_sweep", "baseline"):
                continue
            paid = True
        else:
            if record.stage.value == "pre_filter" and record.code not in SLOT_LOSER_CODES:
                continue  # content rules: never a candidate for a slot
            paid = record.stage.value != "pre_filter"
        snapshot = record.signal
        facet = facet_of_content(snapshot.source_id, snapshot.content or "")
        prior, grounded, _ = priors.prior_for(snapshot.source_id, facet)
        tickers = snapshot_tickers(snapshot)
        candidates.append(
            Candidate(
                decision_id=record.decision_id,
                source_id=snapshot.source_id,
                signal_class=str(snapshot.signal_class),
                facet=facet,
                prior=prior,
                grounded=grounded,
                researched=paid,
                symbol=tickers[0].upper() if tickers else "",
                observed=snapshot.observed_at.date(),
                content_head=(snapshot.content or "").splitlines()[0][:70] if snapshot.content else "",
            )
        )
    actual = [c for c in candidates if c.researched]
    total_slots = len(actual)
    ranked = sorted(candidates, key=lambda c: (-c.prior, c.source_id, c.decision_id))
    chosen: list[Candidate] = []
    per_source: dict[str, int] = {}
    per_class: dict[str, int] = {}
    for candidate in ranked:
        if len(chosen) >= total_slots:
            break
        cap = source_caps.get(candidate.source_id)
        if cap is not None and per_source.get(candidate.source_id, 0) >= cap:
            continue
        if class_caps is not None:
            bucket = class_caps.bucket(candidate.signal_class)
            if per_class.get(bucket, 0) >= class_caps.cap_for(candidate.signal_class):
                continue
            per_class[bucket] = per_class.get(bucket, 0) + 1
        per_source[candidate.source_id] = per_source.get(candidate.source_id, 0) + 1
        chosen.append(candidate)

    def by_source(members: list[Candidate]) -> dict[str, int]:
        out: dict[str, int] = {}
        for m in members:
            out[m.source_id] = out.get(m.source_id, 0) + 1
        return dict(sorted(out.items()))

    def realised(members: list[Candidate], horizon: int) -> tuple[int, Optional[float]]:
        vals = []
        for m in members:
            if not m.symbol:
                continue
            row = rows.get((m.symbol, m.observed))
            mark = row.marks.get(horizon) if row is not None else None
            if mark is not None and mark.excess_pct is not None:
                vals.append(float(mark.excess_pct))
        return len(vals), (sum(vals) / len(vals) if vals else None)

    overlap = {c.decision_id for c in actual} & {c.decision_id for c in chosen}
    lines = [
        f"Dispatch what-if for {day.isoformat()}: {len(candidates)} candidates reached dispatch, "
        f"{total_slots} were researched (the slots), {len(candidates) - total_slots} lost a slot "
        f"(codes {sorted(SLOT_LOSER_CODES)})",
        f"  actual slots by source:  {by_source(actual)}",
        f"  scored slots by source:  {by_source(chosen)}",
        f"  overlap: {len(overlap)} of {total_slots} slots would have gone to the same candidates",
        f"  summed prior (expected {priors.horizon_days}d excess, pct-points): actual "
        f"{sum(c.prior for c in actual):+.2f}, scored {sum(c.prior for c in chosen):+.2f}",
        f"  grounded priors among scored picks: {sum(1 for c in chosen if c.grounded)} of {len(chosen)}",
    ]
    for horizon in (1, 5):
        n_a, m_a = realised(actual, horizon)
        n_s, m_s = realised(chosen, horizon)
        fmt = lambda n, m: f"n={n} mean={m:+.2f}" if m is not None else f"n={n} unresolved"  # noqa: E731
        lines.append(f"  realised excess at {horizon}d: actual {fmt(n_a, m_a)}; scored {fmt(n_s, m_s)}")
    lines.append("  scored picks:")
    for c in chosen:
        mark = "kept" if c.decision_id in overlap else "NEW "
        lines.append(
            f"    {mark} {c.prior:+.2f} {'g' if c.grounded else 'r'} {c.source_id:<26} "
            f"{c.facet or '(source)':<30} {c.symbol:<6} {c.content_head}"
        )
    dropped = [c for c in actual if c.decision_id not in overlap]
    if dropped:
        lines.append("  actual picks the scoring would have dropped:")
        for c in dropped:
            lines.append(
                f"    drop {c.prior:+.2f} {'g' if c.grounded else 'r'} {c.source_id:<26} "
                f"{c.facet or '(source)':<30} {c.symbol:<6} {c.content_head}"
            )
    return "\n".join(lines)
